// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLzBU5ogWqpc6tzwEMGklTXk9YUXFSFxs',
    appId: '1:750002165054:web:0ffa1ab260a87dc411486f',
    messagingSenderId: '750002165054',
    projectId: 'shankar-textiles',
    authDomain: 'shankar-textiles.firebaseapp.com',
    storageBucket: 'shankar-textiles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8wILXkcJg170n2ul1jzuNEFHzjLpdkA',
    appId: '1:750002165054:android:edc0cc7dee483a2211486f',
    messagingSenderId: '750002165054',
    projectId: 'shankar-textiles',
    storageBucket: 'shankar-textiles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsaXw6TxPfy9Msi6xtBI7T3t-TS5phgK4',
    appId: '1:750002165054:ios:a76e3a6a6845c41711486f',
    messagingSenderId: '750002165054',
    projectId: 'shankar-textiles',
    storageBucket: 'shankar-textiles.appspot.com',
    androidClientId: '750002165054-5pduppmgnntlqd2d26mnthdtg8fe5k6a.apps.googleusercontent.com',
    iosClientId: '750002165054-3gc6mc1kavih2jt4lr7l8t8i9p6e4olb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsaXw6TxPfy9Msi6xtBI7T3t-TS5phgK4',
    appId: '1:750002165054:ios:ec78a0d337223c7f11486f',
    messagingSenderId: '750002165054',
    projectId: 'shankar-textiles',
    storageBucket: 'shankar-textiles.appspot.com',
    androidClientId: '750002165054-5pduppmgnntlqd2d26mnthdtg8fe5k6a.apps.googleusercontent.com',
    iosClientId: '750002165054-8vb2q0natbteun7hjv6mno72agisci0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
